apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendsvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendsvc
  template:
    metadata:
      labels:
        app: frontendsvc
    spec:
      containers:
      - name: frontendsvc-container
        image: australia-southeast1-docker.pkg.dev/spendwise-486202/spendwise/frontend:f5328c9
        ports:
        - containerPort: 3080
        env:
        - name: ACCOUNT_SERVICE_URL
          value: "http://accountsvc-service:3330"
        - name: EXPENSE_SERVICE_URL
          value: "http://expensesvc-service:3332"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: frontendsvc-service
spec: 
  type: LoadBalancer
  selector:
    app: frontendsvc
  ports: 
    - port: 3080 # Internal service port -> use for port forwarding
      targetPort: 3080 # Container port