name: Test - Expense Sevice

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/expense_service/**"
      - ".github/workflows/**-expensesvc.yml"

  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/expense_service/**"
      - ".github/workflows/**-expensesvc.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Start MongoDB container
        run: docker run -d -p 27017:27017 --name test-mongo mongo:6
      
      # Test
      - name: Install dependencies for account service
        run: | 
          cd backend/account_service
          npm install

      - name: Run test for expense service
        env:
          PORT: 3032
          NODE_ENV: test
          MONGO_URI: mongodb://localhost:27017/spendwise
        run: | 
          cd backend/expense_service
          npm install
          npm test
      